language: go
go:
  - 1.15.2
os: linux
dist: focal
#
#services:
#  - postgresql
#
install:
  # Add Godeps dependencies to GOPATH and PATH
  - go get -u -t -v ./...
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
#before_script:
#  - psql -c 'create database maila;' -U postgres
script:
  - cd FileService
  - echo hi
  - ls
  - go fmt ./...
  - go test ./test/tests