language: go
sudo: false
go:
- 1.15.2
os: linux
dist: focal
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql
    - postgresql-client
install:
- go get -u -t -v ./...
before_script:
- sudo service postgresql start
- psql -c 'create database maila;' -U postgres
- psql -c "ALTER USER postgres WITH PASSWORD '987654321';" -U postgres
before_install:
- openssl aes-256-cbc -K $encrypted_f627e8db6689_key -iv $encrypted_f627e8db6689_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION

before_deploy:
  - echo before Deploy
  - cd ..
  - pwd
  - ./.ssh/config.ssh
script:
- go mod vendor
- golangci-lint run
- cd cmd
- echo TRAIS BULD DIR
- echo $TRAVIS_BUILD_DIR
#- ./runFileServiceTest.sh
#- "./cmd/runMailServiceTest.sh"
#- "./cmd/runMainApplicationTest.sh"
#- "./cmd/runUserServiceTest.sh"


deploy:
  skip_cleanup: false
  provider: script
  script: ./.travis/deploy.sh
  on:
    branch: CI