language: go

go:
  - 1.15.2
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c 'create database maila;' -U postgres
script:
  - go build FileService/cmd/main.go